const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";
const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_FAIL = "AUTH_FAIL";
const LOG_OUT= "LOG_OUT";
const FILTER_STOCK= "FILTER_STOCK";
export default {
    FETCH_PRODUCTS,
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_FAIL,
    AUTH_SUCCESS,
    AUTH_FAIL,
    LOG_OUT,
    FILTER_STOCK
}
