const FETCH_PRODUCTS = "FETCH_PRODUCTS";
const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

const AUTH_SUCCESS = "AUTH_SUCCESS";
const AUTH_FAIL = "AUTH_FAIL";
const LOG_OUT= "LOG_OUT";

const FILTER_STOCK= "FILTER_STOCK";

const ADD_PRODUCT_START = "ADD_PRODUCT_START";
const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

const EDIT_PRODUCT_START = "EDIT_PRODUCT_START";
const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";

const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

const DIALOG_OPEN = "DIALOG_OPEN";
const DIALOG_CLOSE = "DIALOG_CLOSE";

const EDIT_DIALOG_TRUE = "EDIT_DIALOG_TRUE";
const EDIT_DIALOG_FALSE = "EDIT_DIALOG_FALSE";
const SET_PRODUCT_ID = "SET_PRODUCT_ID";


export default {
    FETCH_PRODUCTS,
    FETCH_PRODUCTS_SUCCESS,
    FETCH_PRODUCTS_FAIL,
    AUTH_SUCCESS,
    AUTH_FAIL,
    LOG_OUT,
    FILTER_STOCK,
    ADD_PRODUCT_START,
    ADD_PRODUCT_SUCCESS,
    ADD_PRODUCT_FAIL,
    EDIT_PRODUCT_START,
    EDIT_PRODUCT_SUCCESS,
    EDIT_PRODUCT_FAIL,
    DELETE_PRODUCT_START,
    DELETE_PRODUCT_SUCCESS,
    DELETE_PRODUCT_FAIL,
    DIALOG_OPEN,
    DIALOG_CLOSE,
    EDIT_DIALOG_TRUE,
    EDIT_DIALOG_FALSE,
    SET_PRODUCT_ID
}
