const FETCH_SPECIFICATIONS = "FETCH_SPECIFICATIONS";
const FETCH_SPECIFICATIONS_FAIL = "FETCH_SPECIFICATIONS_FAIL";
const FETCH_SPECIFICATIONS_SUCCESS = "FETCH_SPECIFICATIONS_SUCCESS";

export default {
    FETCH_SPECIFICATIONS,
    FETCH_SPECIFICATIONS_FAIL,
    FETCH_SPECIFICATIONS_SUCCESS
}
