const FETCH_CATEGORIES = "FETCH_CATEGORIES";
const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";
const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

const FETCH_PRODUCT_CATEGORIES = "FETCH_PRODUCT_CATEGORIES";
const FETCH_PRODUCT_CATEGORIES_FAIL = "FETCH_PRODUCT_CATEGORIES_FAIL";
const FETCH_PRODUCT_CATEGORIES_SUCCESS = "FETCH_PRODUCT_CATEGORIES_SUCCESS";

const EDIT_CATEGORIES_FOR_SERVER = "EDIT_CATEGORIES_FOR_SERVER";

const ADD_CATEGORIES_START = "ADD_CATEGORIES_START";
const ADD_CATEGORIES_FAIL = "ADD_CATEGORIES_FAIL";
const ADD_CATEGORIES_SUCCESS = "ADD_CATEGORIES_SUCCESS";

const FILTER_CATEGORIES_START = "FILTER_CATEGORIES_START";
const FILTER_CATEGORIES_FAIL = "FILTER_CATEGORIES_FAIL";
const FILTER_CATEGORIES_SUCCESS = "FILTER_CATEGORIES_SUCCESS";

export default {
    FETCH_CATEGORIES,
    FETCH_CATEGORIES_FAIL,
    FETCH_CATEGORIES_SUCCESS,
    FETCH_PRODUCT_CATEGORIES,
    FETCH_PRODUCT_CATEGORIES_FAIL,
    FETCH_PRODUCT_CATEGORIES_SUCCESS,
    EDIT_CATEGORIES_FOR_SERVER,
    ADD_CATEGORIES_START,
    ADD_CATEGORIES_FAIL,
    ADD_CATEGORIES_SUCCESS,
    FILTER_CATEGORIES_START,
    FILTER_CATEGORIES_FAIL,
    FILTER_CATEGORIES_SUCCESS,
}