const FETCH_CATEGORIES = "FETCH_CATEGORIES";
const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";
const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";

export default {
    FETCH_CATEGORIES,
    FETCH_CATEGORIES_FAIL,
    FETCH_CATEGORIES_SUCCESS
}